# Generated by Django 5.0.7 on 2024-10-15 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('order_id', models.CharField(blank=True, max_length=50)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=50)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Table_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=10)),
                ('table_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('12:00-1:00pm', '12:00-1:00 PM'), ('1:00-2:00pm', '1:00-2:00 PM'), ('2:00-3:00pm', '2:00-3:00 PM'), ('6:00-7:00pm', '6:00-7:00 PM'), ('7:00-8:00pm', '7:00-8:00 PM'), ('8:00-9:00pm', '8:00-9:00 PM'), ('9:00-10:00pm', '9:00-10:00 PM'), ('10:00-11:00pm', '10:00-11:00 PM')], max_length=15)),
                ('booked_date', models.DateTimeField(auto_now_add=True)),
                ('booking_id', models.CharField(blank=True, max_length=100)),
                ('payment_status', models.CharField(default='pending', max_length=30)),
                ('booking_status', models.CharField(default='pending', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.table_detail')),
            ],
        ),
    ]
