# Generated by Django 5.0.7 on 2024-10-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_booking',
            name='booking_status',
        ),
        migrations.AddField(
            model_name='table_detail',
            name='booking_status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
