# Generated by Django 5.0.7 on 2024-10-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_table_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_booking',
            name='table',
        ),
        migrations.AddField(
            model_name='table_booking',
            name='table',
            field=models.ManyToManyField(to='booking.table_detail'),
        ),
    ]
