# Generated by Django 5.0.7 on 2024-10-19 06:28

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_table_booking_table_table_booking_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_booking',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN'),
        ),
    ]
